### ISSUE TITLE
Editing docs for readability

### ISSUE THREAD

**Issue by shahzaibak** [WeftFinance/weft_docs#1]
I've never done a pull request before so sorry if i fuck up

**Comment by atoumbre** [comment]
No issue.

Contributing to an open-source documentation website involves several steps. Here's a general guide to help you get started:

1. **Familiarize Yourself with the Project:**
   - Visit and read through the existing documentation to understand its structure and style.

2. **Set Up a Local Development Environment:**
   - Clone the repository to your local machine.

3. **Identify Areas for Improvement:**
   - Look for outdated or missing information in the documentation.
   - Check for typos, grammatical errors, or unclear passages.
   - Review open issues and see if there are any documentation-related tasks.

4. **Create a Fork:**
   - Fork the repository on GitHub by clicking the "Fork" button on the project's GitHub page.

5. **Create a Branch:**
   - Create a new branch for your changes. This helps keep your contributions isolated and makes it easier for maintainers to review.

6. **Make Changes:**
   - Use a text editor or integrated development environment (IDE) to make your changes.
   - Ensure that your changes align with the project's coding style and documentation guidelines.

7. **Test Your Changes:**
   - If applicable, test any code snippets or commands provided in the documentation to ensure accuracy.
   - Check that your changes did not introduce new issues.

8. **Commit Your Changes:**
   - Commit your changes to your local branch with clear and descriptive commit messages.

9. **Push Changes to Your Fork:**
   - Push your local branch to your fork on GitHub.

10. **Create a Pull Request:**
    - On GitHub, navigate to your fork and branch, then click the "New Pull Request" button.
    - Provide a descriptive title and summary of your changes in the pull request description.
    - Reference any related issues, if applicable.

11. **Engage in Discussion:**
    - Be responsive to comments and feedback from maintainers.
    - Be open to making additional changes based on feedback.

12. **Address Feedback:**
    - If the maintainers request changes, make the necessary adjustments in your local branch and push the changes.

13. **Merge:**
    - Once your changes are approved, the maintainers will merge your pull request into the main documentation repository.

14. **Celebrate and Stay Involved:**
    - Congratulations! Your contribution is now part of the project.
    - Consider staying involved by addressing more issues, improving documentation, or contributing in other ways.

Remember to be patient and respectful throughout the process. Open source contributions often involve collaboration, and maintaining good communication is key to a positive experience for everyone involved.
